	name: CI
on: [push]
jobs:
  k8s_yaml_validator:
    runs-on: ubuntu-latest
    steps:
      - name: login to Github Packages
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      
      - uses: actions/checkout@v2
      - uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          entrypoint: '/kubeconform'
          args: "-summary -output json k8s/"
  
  secret_scanning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
 
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
    
  build_image:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile
          push: false
          tags: app-localã€€
Additional
Status Badge
Shell Script (welcome to SA)
Open Source Project Workflow
ex. https://github.com/kubernetes/kubernetes

Read CONTRIBUTING.md, LICENSE, and Code of Conduct.
Fork repo to your account.
Clond to your dev environment (ex. your laptop).
Create branch and coding.
Push branch and create PR (your repo -> project official repo).
Review by everyone.
Approve and Merge.
