name: Actions-Example

on: [workflow_dispatch]

jobs:
  job-A:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Job A
        uses: ./.github/workflows/check-status/
        with:
          status: ${{ vars.A }}

  job-B:
    runs-on: ubuntu-latest
    needs: job-A
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Job B
        uses: ./.github/workflows/check-status/
        with:
          status: ${{ vars.B }}

  job-C:
    runs-on: ubuntu-latest
    needs: job-B
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Job C
        uses: ./.github/workflows/check-status/
        with:
          status: ${{ vars.C }}

  job-D:
    runs-on: ubuntu-latest
    needs: job-B
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Job D
        uses: ./.github/workflows/check-status/
        with:
          status: ${{ vars.D }}
